# This list is derived from [[Category:States of the United States]]
# with a little bit of manual post-processing to remove some
# extraneous entries and add a few (not technically states) that were missing.

STATES = frozenset(
    [
        "Alabama",
        "Alaska",
        "Arizona",
        "Arkansas",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "Florida",
        "Georgia (U.S. state)",
        "Hawaii",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York (state)",
        "North Carolina",
        "North Dakota",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Vermont",
        "Virginia",
        "Washington (state)",
        "West Virginia",
        "Wisconsin",
        "Wyoming",
        # Other areas (not technically states)
        "Washington, D.C.",
        "Puerto Rico",
        "Northern Mariana Islands",
        "Guam",
        "American Samoa",
    ]
)
